# fly.toml

app = "wanli-staging"
primary_region = "sin" # Singapore

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"
  [build.args]
    # This line tells the buildpack to look inside the 'backend' module for the final .jar file
    BP_MAVEN_BUILT_MODULE = "backend"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/actuator/health"
