# fly.toml - Correct version for Wanli Academy

app = "wanli-staging"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"
  [build.args]
    BP_MAVEN_BUILT_MODULE = "backend"

[env]
  BPL_JVM_THREAD_COUNT = "50"
  # Database configuration will be automatically injected by Fly.io
  # DATABASE_URL is set automatically when PostgreSQL is attached
  SPRING_PROFILES_ACTIVE = "production"
  SPRING_JPA_HIBERNATE_DDL_AUTO = "update"
  SPRING_JPA_SHOW_SQL = "false"
  SPRING_JPA_DATABASE_PLATFORM = "org.hibernate.dialect.PostgreSQLDialect"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/actuator/health"