# fly.toml

app = "wanli-staging"
primary_region = "sin" # Singapore

[build]
  builder = "paketobuildpacks/builder-jammy-base:latest"
  [build.args]
    BP_MAVEN_BUILT_MODULE = "backend"

# This new [env] section passes environment variables to the running application
[env]
  # This tells the Paketo memory calculator to allocate space for 50 threads, not the default 250
  BPL_JVM_THREAD_COUNT = "50"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/actuator/health"
