[providers]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.install]
cmds = ["ls -la target/", "find target -name '*.jar' -type f"]

[start]
cmd = "java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=production -Dmanagement.server.port=$PORT -jar $(find target -name '*.jar' -type f | head -1)"