[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean compile", "mvn package -DskipTests"]

[phases.install]
cmds = ["find target/ -name '*.jar' -type f"]

[start]
cmd = "java -Xmx300m -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Dserver.port=$PORT -Dspring.profiles.active=production -jar $(find target/ -name '*.jar' -type f | head -1)"