[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.build]
cmds = [
    'mvn clean compile -DskipTests',
    'mvn package -DskipTests'
]

[start]
cmd = 'java -jar target/wanli-academy-backend-0.0.1-SNAPSHOT.jar'

[variables]
MAVEN_OPTS = '-Xmx1024m'
JAVA_OPTS = '-Xmx512m -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai'