[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.install]
cmds = ["ls -la target/", "find target/ -name '*.jar' -type f"]

[start]
cmd = "java -Xmx300m -Dserver.port=$PORT -Dspring.profiles.active=production -jar $(find target/ -name '*.jar' -type f | head -1)"