[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.install]
cmds = ["ls -la target/"]

[start]
cmd = "java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=production -Dmanagement.server.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar"
